;;; -*- coding: utf-8; mode: lisp-data -*-
(("c:/Users/25670/CodeSpace/game-server/server/services/api/admin/internal/logic/data/getPlayInfoArrayLogic.go"
  . 608)
 ("c:/Users/25670/CodeSpace/game-server/server/services/rpc/user/internal/logic/thirdLoginByAccountLogic.go"
  . 8212)
 ("c:/Users/25670/CodeSpace/game-server/"
  (dired-filename . "c:/Users/25670/CodeSpace/game-server/server"))
 ("c:/Program Files/Emacs/"
  (dired-filename . "c:/Program Files/Emacs/emacs-31.0.50"))
 ("c:/Users/25670/.emacs.d/lisp/init-lsp-bridge.el" . 1157)
 ("c:/Users/25670/CodeSpace/common/"
  (dired-filename . "c:/Users/25670/CodeSpace/common/README.md"))
 ("c:/Users/25670/" (dired-filename . "c:/Users/25670/CodeSpace"))
 ("c:/Users/25670/CodeSpace/"
  (dired-filename . "c:/Users/25670/CodeSpace/go-learn"))
 ("c:/Users/25670/CodeSpace/go-learn/"
  (dired-filename . "c:/Users/25670/CodeSpace/go-learn/main.go"))
 ("c:/Users/25670/CodeSpace/go-learn/main.go" . 42)
 ("c:/Users/25670/CodeSpace/game-server/server/services/api/admin/internal/logic/data/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-server/server/services/api/admin/internal/logic/data"))
 ("c:/Users/25670/CodeSpace/game-server/server/services/api/admin/internal/logic/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-server/server/services/api/admin/internal/logic/data"))
 ("c:/Users/25670/CodeSpace/game-server/server/services/api/admin/internal/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-server/server/services/api/admin/internal/logic"))
 ("c:/Users/25670/CodeSpace/game-server/server/services/api/admin/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-server/server/services/api/admin/internal"))
 ("c:/Users/25670/CodeSpace/game-server/server/services/api/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-server/server/services/api/admin"))
 ("c:/Users/25670/CodeSpace/game-server/server/services/"
  (dired-filename . "c:/Users/25670/CodeSpace/game-server/server/services/api"))
 ("c:/Users/25670/CodeSpace/game-server/server/"
  (dired-filename . "c:/Users/25670/CodeSpace/game-server/server/services"))
 ("c:/Users/25670/.emacs.d/lisp/init-completion.el" . 280)
 ("c:/Program Files/" (dired-filename . "c:/Program Files/Emacs"))
 ("c:/" (dired-filename . "c:/Users"))
 ("c:/Users/" (dired-filename . "c:/Users/25670"))
 ("c:/Users/25670/.emacs.d/" (dired-filename . "c:/Users/25670/.emacs.d/lisp"))
 ("c:/Users/25670/.emacs.d/lisp/"
  (dired-filename . "c:/Users/25670/.emacs.d/lisp/init-lsp-bridge.el"))
 ("c:/Users/25670/.emacs.d/site-lisp/"
  (dired-filename . "c:/Users/25670/.emacs.d/site-lisp/lsp-bridge"))
 ("c:/Users/25670/.emacs.d/site-lisp/lsp-bridge/"
  (dired-filename
   . "c:/Users/25670/.emacs.d/site-lisp/lsp-bridge/lsp-bridge-call-hierarchy.el"))
 ("c:/Users/25670/.CocosCreator/"
  (dired-filename . "c:/Users/25670/.CocosCreator/editor"))
 ("c:/ProgramData/" (dired-filename . "c:/ProgramData/Apple Inc"))
 ("c:/Users/25670/.emacs.d/lsp-bridge/"
  (dired-filename . "c:/Users/25670/.emacs.d/lsp-bridge/remote_file"))
 ("c:/Users/25670/.emacs.d/eln-cache/31.0.50-5c057e1d/"
  (dired-filename
   . "c:/Users/25670/.emacs.d/eln-cache/31.0.50-5c057e1d/annalist-d7146180-001b5653.eln"))
 ("c:/Users/25670/.emacs.d/eln-cache/"
  (dired-filename . "c:/Users/25670/.emacs.d/eln-cache/31.0.50-5c057e1d"))
 ("c:/Users/25670/.emacs.d/bin/"
  (dired-filename . "c:/Users/25670/.emacs.d/bin/conpty_proxy.exe"))
 ("c:/Users/25670/.emacs.d/auto-save-list/"
  (dired-filename
   . "c:/Users/25670/.emacs.d/auto-save-list/.saves-41096-APPLE115~"))
 ("c:/Users/25670/CodeSpace/game-web-admin/src/App.vue" . 299)
 ("c:/Program Files/Emacs/emacs-31.0.50/bin/"
  (dired-filename . "c:/Program Files/Emacs/emacs-31.0.50/bin/addpm.exe"))
 ("c:/Users/25670/.emacs.d/lsp-proxy/languages.toml" . 17163)
 ("c:/Users/25670/.emacs.d/lsp-proxy/"
  (dired-filename . "c:/Users/25670/.emacs.d/lsp-proxy/languages.toml"))
 ("c:/Users/25670/CodeSpace/game-web-admin/src/components/table/add-table/index.vue"
  . 1716)
 ("c:/Users/25670/CodeSpace/game-web-admin/src/views/system/users/list/index.vue"
  . 5501)
 ("c:/Users/25670/CodeSpace/game-web-admin/src/views/data-center/rtp/index.vue"
  . 2381)
 ("c:/Users/25670/CodeSpace/game-web-admin/"
  (dired-filename . "c:/Users/25670/CodeSpace/game-web-admin/src"))
 ("c:/Users/25670/.emacs.d/lisp/init-tools.el" . 438)
 ("c:/Users/25670/.emacs.d/lisp/init-project.el" . 1808)
 ("c:/Users/25670/CodeSpace/game-server/server/services/rpc/gameAdmin/internal/logic/recordBuildTaskLogic.go"
  . 2139)
 ("c:/Users/25670/.emacs.d/lisp/init-ai.el" . 1629)
 ("c:/Users/25670/CodeSpace/game-server/server/services/api/gameBuild/internal/handler/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-server/server/services/api/gameBuild/internal/handler/build"))
 ("c:/Users/25670/CodeSpace/game-server/server/services/api/gameBuild/internal/logic/common_test.go"
  . 16)
 ("c:/Users/25670/CodeSpace/game-server/server/services/api/gameBuild/internal/logic/config.go"
  . 1463)
 ("c:/Users/25670/CodeSpace/game-server/server/services/api/gameBuild/internal/logic/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-server/server/services/api/gameBuild/internal/logic/config.go"))
 ("c:/Users/25670/CodeSpace/game-server/server/services/api/gameBuild/internal/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-server/server/services/api/gameBuild/internal/logic"))
 ("c:/Users/25670/CodeSpace/game-server/server/services/api/gameBuild/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-server/server/services/api/gameBuild/internal"))
 ("c:/Users/25670/.emacs.d/eshell/"
  (dired-filename . "c:/Users/25670/.emacs.d/eshell/history"))
 ("c:/Users/25670/.emacs.d/elpa/"
  (dired-filename . "c:/Users/25670/.emacs.d/elpa/ace-window-20220911.358"))
 ("c:/Users/25670/emacs-build/"
  (dired-filename . "c:/Users/25670/emacs-build/build-dist.sh"))
 ("c:/Users/25670/.emacs.d/snippets/"
  (dired-filename . "c:/Users/25670/.emacs.d/snippets/emacs-lisp-mode"))
 ("c:/Users/25670/.emacs.d/tree-sitter/" . 135)
 ("c:/Users/25670/CodeSpace/game-web-admin/src/views/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-web-admin/src/views/dashboard"))
 ("c:/Users/25670/CodeSpace/game-web-admin/src/"
  (dired-filename . "c:/Users/25670/CodeSpace/game-web-admin/src/views"))
 ("c:/Users/25670/CodeSpace/game-web-admin/src/views/data-center/rtp/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-web-admin/src/views/data-center/rtp/index.vue"))
 ("c:/Users/25670/CodeSpace/game-web-admin/src/views/data-center/" . 210)
 ("c:/Users/25670/CodeSpace/game-server/server/services/rpc/gameAdmin/internal/logic/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-server/server/services/rpc/gameAdmin/internal/logic/recordBuildTaskLogic.go"))
 ("c:/Users/25670/CodeSpace/game-server/server/services/rpc/gameAdmin/internal/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-server/server/services/rpc/gameAdmin/internal/logic"))
 ("c:/Users/25670/CodeSpace/game-server/server/services/rpc/gameAdmin/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-server/server/services/rpc/gameAdmin/internal"))
 ("c:/Users/25670/CodeSpace/game-server/server/services/rpc/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-server/server/services/rpc/gameAdmin"))
 ("c:/Users/25670/CodeSpace/game-server/server/services/api/gameBuild/internal/middleware/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-server/server/services/api/gameBuild/internal/middleware/corsMiddleware.go"))
 ("c:/Users/25670/CodeSpace/game-server/server/services/api/gameBuild/internal/logic/build_bundle.py"
  . 1274)
 ("c:/Program Files/Emacs/emacs-31.0.50/"
  (dired-filename . "c:/Program Files/Emacs/emacs-31.0.50"))
 ("c:/Program Files/Git/bin/"
  (dired-filename . "c:/Program Files/Git/bin/sh.exe"))
 ("c:/Program Files/Git/" (dired-filename . "c:/Program Files/Git/bin"))
 ("c:/Users/25670/.emacs.d/lisp/init-git.el" . 312)
 ("c:/Users/25670/CodeSpace/game-web-admin/src/components/input/" . 222)
 ("c:/Users/25670/CodeSpace/game-web-admin/src/components/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-web-admin/src/components/input"))
 ("c:/Users/25670/CodeSpace/game-web-admin/src/layout/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-web-admin/src/layout/default-layout.vue"))
 ("c:/Users/25670/CodeSpace/oneKey/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/oneKey/bundle-build-config-fish_main.json"))
 ("c:/Users/Default/" (dired-filename . "c:/Users/Default/Cookies"))
 ("c:/Users/25670/CodeSpace/game-server/server/script/build.sh" . 90)
 ("c:/Users/25670/CodeSpace/game-server/server/script/" . 595)
 ("c:/Users/25670/.emacs.d/lisp/init-ui.el" . 387)
 ("c:/Users/Public/" (dired-filename . "c:/Users/Public/AccountPictures"))
 ("c:/Users/25670/CodeSpace/game-web-admin/src/views/system/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-web-admin/src/views/system/api-log"))
 ("c:/Users/25670/CodeSpace/game-web-admin/src/views/game/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-web-admin/src/views/game/games"))
 ("c:/Users/25670/CodeSpace/game-web-admin/src/views/exception/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-web-admin/src/views/exception/403"))
 ("c:/Users/25670/CodeSpace/game-web-admin/src/views/dashboard/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-web-admin/src/views/dashboard/workplace"))
 ("c:/Users/25670/CodeSpace/game-web-admin/src/views/config/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-web-admin/src/views/config/bucket"))
 ("c:/Users/25670/CodeSpace/game-web-admin/src/views/agent/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-web-admin/src/views/agent/agents"))
 ("c:/Users/25670/CodeSpace/game-web-admin/src/views/agent/agents/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-web-admin/src/views/agent/agents/list"))
 ("c:/Users/25670/CodeSpace/game-web-admin/src/views/agent/agents/list/"
  (dired-filename
   . "c:/Users/25670/CodeSpace/game-web-admin/src/views/agent/agents/list/index.vue"))
 ("c:/Users/25670/CodeSpace/game-web-admin/src/views/agent/agents/list/index.vue"
  . 11555)
 ("c:/Windows/" (dired-filename . "c:/"))
 ("c:/Users/25670/CodeSpace/game-server/server/script/build.bat" . 1079)
 ("c:/Users/25670/CodeSpace/game-web-admin/index.html" . 354)
 ("c:/Users/25670/.emacs.d/lisp/init-edit.el" . 2547))
